DROP SCHEMA IF EXISTS cmn CASCADE;
CREATE SCHEMA cmn;
CREATE TABLE IF NOT EXISTS cmn.Roles
(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY 	
	, Name              TEXT        UNIQUE       	
	, Const 			TEXT 		UNIQUE
	, PRIMARY KEY (ID)
) WITH (OIDS=FALSE, FILLFACTOR=90);

/*
const (
	Guest    = iota // Гость
	Admin           // Администратор
	Reg             // Зарегистрированный
	Auth            // Авторизованный
	Employee        // Сотрудник
)
*/

INSERT INTO cmn.Roles
(
	ID, Name, Const
)
VALUES 
(0, 'Гость', 'Guest'),
(1, 'Администратор', 'Admin'),
(2, 'Зарегистрированный пользователь', 'Reg'),
(3, 'Авторизованный пользователь', 'Auth'),
(4, 'Сотрудник', 'Employee');

CREATE TABLE IF NOT EXISTS cmn.Users 
(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY 
	, RoleID 				INT			
	, Login                 TEXT        	UNIQUE 
	, Password              TEXT       		
	, Name                  TEXT 
	, FamilyName			TEXT
	, PatronName			TEXT    		  		
	, Email                 TEXT 			UNIQUE    		
	, Phone		            TEXT      					         
	, PRIMARY KEY (ID)
	, FOREIGN KEY (RoleID) REFERENCES cmn.Roles(ID) DEFERRABLE
) WITH (OIDS=FALSE, FILLFACTOR=90) 
;
CREATE INDEX IF NOT EXISTS idx_users_id ON cmn.Users (ID);
CREATE INDEX IF NOT EXISTS  idx_users_login ON cmn.Users (Login) INCLUDE (Password);

CREATE TABLE IF NOT EXISTS cmn.Sessions
(
ID BIGINT 			NOT NULL GENERATED BY DEFAULT AS IDENTITY 
, UserID     		INT
, LoginTime 		TIMESTAMPTZ
, ActionTime 		TIMESTAMPTZ
, LogoutTime		TIMESTAMPTZ
, PRIMARY KEY (ID)
, FOREIGN KEY (UserID) REFERENCES cmn.Users(ID) DEFERRABLE
) WITH (OIDS=FALSE, FILLFACTOR=90) 
;
CREATE INDEX IF NOT EXISTS idx_sessions_id ON cmn.Sessions (ID) INCLUDE (LoginTime, ActionTime, LogoutTime);

CREATE TABLE IF NOT EXISTS cmn.Teams 
(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY     		
	, Name                  TEXT  UNIQUE  					         
	, PRIMARY KEY (ID)
) WITH (OIDS=FALSE, FILLFACTOR=90);

CREATE TABLE IF NOT EXISTS cmn.UserTeams 
(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY     		
	, UserID                  INT   NOT NULL   					         
	, TeamID				  INT   NOT NULL
	, PRIMARY KEY (ID)
	, FOREIGN KEY (UserID) REFERENCES cmn.Users(ID) DEFERRABLE
	, FOREIGN KEY (TeamID) REFERENCES cmn.Teams(ID) DEFERRABLE
) WITH (OIDS=FALSE, FILLFACTOR=90);