-- Table: cmn.roles

-- DROP TABLE IF EXISTS cmn.roles;

CREATE TABLE IF NOT EXISTS cmn.roles
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    c_name text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)

WITH (
    FILLFACTOR = 90
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS cmn.roles
    OWNER to postgres;

COMMENT ON TABLE cmn.roles
    IS 'Роли пользователя';

COMMENT ON COLUMN cmn.roles.id
    IS 'Уникальный идентификатор';

COMMENT ON COLUMN cmn.roles.c_name
    IS 'Наименование роли пользователя';


-- Table: cmn.sessions

-- DROP TABLE IF EXISTS cmn.sessions;

CREATE TABLE IF NOT EXISTS cmn.sessions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    userid integer,
    d_login timestamp with time zone,
    d_last timestamp with time zone,
    d_logout timestamp with time zone,
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_userid_fkey FOREIGN KEY (userid)
        REFERENCES cmn.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE
)

WITH (
    FILLFACTOR = 90
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS cmn.sessions
    OWNER to postgres;

COMMENT ON TABLE cmn.sessions
    IS 'Сессии пользователей';

COMMENT ON COLUMN cmn.sessions.id
    IS 'Уникальный идентификатор';

COMMENT ON COLUMN cmn.sessions.d_login
    IS 'Дата и время логина пользователя';

COMMENT ON COLUMN cmn.sessions.d_last
    IS 'Дата и время последнего действия пользователя';

COMMENT ON COLUMN cmn.sessions.d_logout
    IS 'Дата и время выхода пользователя';

    -- Table: cmn.users

-- DROP TABLE IF EXISTS cmn.users;

CREATE TABLE IF NOT EXISTS cmn.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    roleid smallint NOT NULL,
    c_login text COLLATE pg_catalog."default",
    c_surname text COLLATE pg_catalog."default",
    c_name text COLLATE pg_catalog."default",
    c_patronymic text COLLATE pg_catalog."default",
    c_email text COLLATE pg_catalog."default",
    c_phone text COLLATE pg_catalog."default",
    c_password text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_c_login_key UNIQUE (c_login),
    CONSTRAINT users_roleid_fkey FOREIGN KEY (roleid)
        REFERENCES cmn.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE
)

WITH (
    FILLFACTOR = 90
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS cmn.users
    OWNER to postgres;

COMMENT ON TABLE cmn.users
    IS 'Пользователи';

COMMENT ON COLUMN cmn.users.id
    IS 'Уникальный идентификатор';

COMMENT ON COLUMN cmn.users.c_login
    IS 'Логин';

COMMENT ON COLUMN cmn.users.c_surname
    IS 'Фамилия';

COMMENT ON COLUMN cmn.users.c_name
    IS 'Имя';

COMMENT ON COLUMN cmn.users.c_patronymic
    IS 'Отчество';

COMMENT ON COLUMN cmn.users.c_email
    IS 'Адрес электронной почты';

COMMENT ON COLUMN cmn.users.c_phone
    IS 'Телефон';

COMMENT ON COLUMN cmn.users.c_password
    IS 'Пароль';
